[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
[window.padding]
x = 5
y = 5

[cursor]
style = "Beam"

[font]
size = 11

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[mouse]
hide_when_typing = true

[general]
import = ["~/.config/alacritty/themes/themes/gruber_darker.toml"]
