# Wallpaper
output * bg ~/Pictures/skies.png fill

# Display Configurations
output DP-2 mode 3440x1440@120.000Hz
output eDP-1 mode 1920x1080@48.008Hz

# Display Settings Menu Binding
bindsym XF86Display exec wdisplays

# Clamshell Mode
exec_always ~/.config/sway/scripts/clamshell-reloadfix.sh
bindswitch --reload --locked lid:on output eDP-1 disable
bindswitch --reload --locked lid:off output eDP-1 enable
