# Floating Window Rules
for_window [app_id="blueman-manager"] floating enable, move position 75% 0%, resize set width 30% height 40%
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable, move position 75% 0%, resize set width 30% height 40%
for_window [app_id="nwg-displays"] floating enable, move position 75% 0%, resize set width 30% height 40%
for_window [app_id="com.github.wwmm.easyeffects"] floating enable
for_window [app_id="launcher"] floating enable, sticky enable, move position center, resize set 400 px 500 px
for_window [app_id="powermenu"] floating enable, sticky enable, move position center, resize set 200 px 200 px

# Inhibit idle for fullscreen apps (e.g. YouTube, Games)
for_window [app_id=".*"] inhibit_idle fullscreen
for_window [class=".*"] inhibit_idle fullscreen
