# --- System Services ---
# Fix for apps not seeing the Wayland session (screen sharing, etc.)
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway GTK_THEME
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK

# Notification Daemon
exec dunst

# Foot server
exec foot --server

# Display Management (Kanshi)
exec_always pkill kanshi
exec_always kanshi
