# ~/.config/foot/themes/kanagawa_wave.ini
# from: https://github.com/rebelot/kanagawa.nvim

[colors-dark]
background=1f1f28
foreground=dcd7ba

## Normal colors
regular0=090618  # black (sumiInk0)
regular1=c34043  # red (autumnRed)
regular2=76946a  # green (autumnGreen)
regular3=c0a36e  # yellow (boatYellow2)
regular4=7e9cd8  # blue (crystalBlue)
regular5=957fb8  # magenta (oniViolet)
regular6=6a9589  # cyan (waveAqua1)
regular7=c8c093  # white (oldWhite)

## Bright colors
bright0=727169   # bright black (fujiGray)
bright1=e82424   # bright red (peachRed)
bright2=98bb6c   # bright green (springGreen)
bright3=e6c384   # bright yellow (carpYellow)
bright4=7fb4ca   # bright blue (springBlue)
bright5=938aa9   # bright magenta (springViolet1)
bright6=7aa89f   # bright cyan (waveAqua2)
bright7=dcd7ba   # bright white (fujiWhite)
