[colors-dark]
# Base
background=282c34
foreground=abb2bf

# Normal colors
regular0=282c34
regular1=e06c75
regular2=98c379
regular3=e5c07b
regular4=61afef
regular5=c678dd
regular6=56b6c2
regular7=abb2bf

# Bright colors
bright0=5c6370
bright1=e06c75
bright2=98c379
bright3=e5c07b
bright4=61afef
bright5=c678dd
bright6=56b6c2
bright7=ffffff

# Selection and Cursor colors
selection-foreground=abb2bf
selection-background=3e4452
cursor=282c34 528bff
